### PR TITLE
WIP: TSLint to ESLint migration

### PR DESCRIPTION
**Pull request by charlex**
## Description

For #134 

## Checklist

- [x] I have read the [**contributing**][contributing] document.
- [x] My code follows the code style of this project and `yarn fix` runs successfully.
- [ ] I have updated the documentation where necessary.
- [ ] New code is unit tested and all current tests pass when running `yarn test` .

Todos:

- [ ] Configure and decide on new ESLint rules
- [ ] Update any TSLint line ignores to new ESLint style
- [ ] Remove TSLint

## Screenshots

[contributing]: https://github.com/ifiokjr/remirror/blob/master/docs/pages/contributing.md

### CODE REVIEW

**Comment by charlex** [comment]
Alright, made a little progress and as per https://github.com/ifiokjr/remirror/issues/134#issuecomment-517936554 , I have began to remove individual lint scripts from nested package.json files in this commit (just for an example) https://github.com/ifiokjr/remirror/pull/139/commits/ffb259abd10c937faa9c6667e8107d283c3e81da.


Will hopefully have some time later in the day to sink into this.

**Comment by ifiokjr** [comment]
@charlex 
Thanks for the work on this. For the initial PR it might be easiest to create the eslint rules alongside the tslint rules. The eslint rules would check that the code is up to standard but wouldn't automatically fix things. 

Once we're happy that the new eslint rules replicate or enhance the project it's then a case of

1. switching off tslint and turning on eslint exclusively
2. removing all tslint leftovers from the project


This would take place in a seperate PR.

**Comment by charlex** [comment]
@ifiokjr Smart! Yeah, I think this PR got a bit unwieldily.  

Should we just start ESLint with the bare minimum rules that the project already conforms to?

**Comment by charlex** [comment]
Closing this in favor of https://github.com/ifiokjr/remirror/pull/140

**Comment by benjie** [comment]
You might want to check out https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin-tslint which allows you to continue using your TSLint rules inside of ESLint; it can make migration easier.

**Comment by ifiokjr** [comment]
Nice suggestion @benjie! I had completely forgotten this was an option. The only gripe is the lack of auto-fix which might get annoying, so perhaps fixable rules should be migrated over but the rest can stay as they are.

**Pull request closed without merging**
